### ISSUE TITLE
Make MusicBrainz Webservice URL Configurable

### ISSUE THREAD

**Issue by loadfix** [Dremora/foo_musicbrainz#53]
Firstly, amazing plugin, well done!

For those of us who maintain our own MusicBrainz mirror, it would be great if MusicBrainz server location could be configurable. so that we don't have to recompile the plugin or mess with host files.

**Comment by Dremora** [comment]
Thanks for the feedback!

I don't maintain this plugin anymore, but check out [this fork](https://github.com/19379/foo_musicbrainz).

**Comment by loadfix** [comment]
Thanks for the quick response! Will check out the fork.

**Comment by Efreak** [comment]
You might consider archiving the repository and/or leaving a note in the readme. Unfortunately, the current fork by @kbuffington doesn't seem to have issues enabled; finding this was made slightly more difficult due to it not being linked as a fork in github.

**Comment by Dremora** [comment]
Good point on archiving the repo! I will do it now and provide the link to @kbuffington's [fork](https://github.com/kbuffington/foo_musicbrainz). In regards to the issues not being enabled, have a look at the [Hydrogenaudio forum thread](https://hydrogenaud.io/index.php/topic,70623.0.html).
